import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.scss";
import { AntdRegistry } from "@ant-design/nextjs-registry";
const inter = Inter({ subsets: ["latin"] });
import "normalize.css";
import "./global.scss";
import "./layout.scss";
import "./mobile.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="app">
          <div className="layout_container mobile">
            <AntdRegistry>{children}</AntdRegistry>
          </div>
        </div>
      </body>
    </html>
  );
}
