import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.scss";
import { AntdRegistry } from "@ant-design/nextjs-registry";
const inter = Inter({ subsets: ["latin"] });
import "normalize.css";
import styles from "./layout.module.scss";
import "./layout.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} id="#app">
        <div className={styles.layout_container}>
          <AntdRegistry>{children}</AntdRegistry>
        </div>
      </body>
    </html>
  );
}
