/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    CommonButtonItem: typeof import('./components/CommonButtonItem.vue')['default']
    CommonTextLoading: typeof import('./components/CommonTextLoading.vue')['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HaitongUniTrustAvatar: typeof import('./components/HaitongUniTrustAvatar.vue')['default']
    HaitongUnitrustHorseAvatar: typeof import('./components/HaitongUnitrustHorseAvatar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitLine: typeof import('./components/SplitLine.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
    Welcome: typeof import('./components/Welcome.vue')['default']
    WelcomeNew: typeof import('./components/WelcomeNew.vue')['default']
    WenXinAvatar: typeof import('./components/WenXinAvatar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
